---
- name: Update all system packages (apt upgrade)
  apt:
    upgrade: dist
    update_cache: yes
  become: yes

- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes
  become: yes

- name: Copy custom default site config
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644
  notify: Restart nginx

- name: Copy custom nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart nginx
